/**
 * Pay On Demand for Digital Inclusion
 * Please visit https://developer.mastercard.com for additional details. ## Usage Notes - In the endpoints, you will see parameter examples in {{parameter}} format. You need to replace that with the actual value. This is usually applicable for identifier (ID). For example, on GET /contracts, you need to replace \"financier_id\" parameter with actual financier ID value. You can get this value either from querying using GET /financiers or creating a new financier using POST /financiers. The same applies for properties inside request body. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: PayonDemand_DigitalInclusion@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ContractDevice', 'model/InstalmentContractDetail'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ContractDevice'), require('./InstalmentContractDetail'));
  } else {
    // Browser globals (root is window)
    if (!root.PodApiClient) {
      root.PodApiClient = {};
    }
    root.PodApiClient.Contract = factory(root.PodApiClient.ApiClient, root.PodApiClient.ContractDevice, root.PodApiClient.InstalmentContractDetail);
  }
}(this, function(ApiClient, ContractDevice, InstalmentContractDetail) {
  'use strict';



  /**
   * The Contract model module.
   * @module model/Contract
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Contract</code>.
   * @alias module:model/Contract
   * @class
   * @param id {String} ID.
   * @param amount {Number} Total payment amount. Formatted according to ISO 4217 standard.
   * @param currency {String} Currency in ISO 4217 format.
   * @param downpaymentAmount {Number} Amount of downpayment. Formatted according to ISO 4217 standard.
   * @param duration {Number} Length of contract duration based on duration unit chosen. Minimum value is 1.
   * @param durationUnit {String} Time unit for length of contract. It can be DAY, WEEK or MONTH.
   * @param financierId {String} Financier ID that owns this contract.
   * @param startDate {Date} Date time when contract is started. Default is null.
   * @param status {String} Status of contract. - CREATED; Contract is created but not started. - ACTIVE; Contract is started and active. - INACTIVE; Contract is started but inactive. Credit is not deducted and payment schedules are not active. Payment can no longer be made. - CANCELED; Contract is canceled. Credit is not deducted and payment schedules are not active. Payment can no longer be made. - COMPLETED; Contract is completed. Credit is not deducted and payment schedules are not active. Payment can no longer be made.  Default is CREATED 
   * @param totalPaidAmount {Number} Total amount paid. This is derived from the total amount of transactions happen for this contract.
   * @param type {String} Type of contract. Determine how payment is done. It can be CREDIT or INSTALMENT.
   */
  var exports = function(id, amount, currency, downpaymentAmount, duration, durationUnit, financierId, startDate, status, totalPaidAmount, type) {
    var _this = this;

    _this['id'] = id;
    _this['amount'] = amount;
    _this['currency'] = currency;
    _this['downpaymentAmount'] = downpaymentAmount;
    _this['duration'] = duration;
    _this['durationUnit'] = durationUnit;
    _this['financierId'] = financierId;
    _this['startDate'] = startDate;
    _this['status'] = status;
    _this['totalPaidAmount'] = totalPaidAmount;
    _this['type'] = type;
  };

  /**
   * Constructs a <code>Contract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Contract} obj Optional instance to populate.
   * @return {module:model/Contract} The populated <code>Contract</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
      if (data.hasOwnProperty('currency')) {
        obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
      }
      if (data.hasOwnProperty('defaultPaymentMethodId')) {
        obj['defaultPaymentMethodId'] = ApiClient.convertToType(data['defaultPaymentMethodId'], 'String');
      }
      if (data.hasOwnProperty('device')) {
        obj['device'] = ContractDevice.constructFromObject(data['device']);
      }
      if (data.hasOwnProperty('downpaymentAmount')) {
        obj['downpaymentAmount'] = ApiClient.convertToType(data['downpaymentAmount'], 'Number');
      }
      if (data.hasOwnProperty('downpaymentTransactionId')) {
        obj['downpaymentTransactionId'] = ApiClient.convertToType(data['downpaymentTransactionId'], 'String');
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
      }
      if (data.hasOwnProperty('durationUnit')) {
        obj['durationUnit'] = ApiClient.convertToType(data['durationUnit'], 'String');
      }
      if (data.hasOwnProperty('financierId')) {
        obj['financierId'] = ApiClient.convertToType(data['financierId'], 'String');
      }
      if (data.hasOwnProperty('instalmentContractDetails')) {
        obj['instalmentContractDetails'] = InstalmentContractDetail.constructFromObject(data['instalmentContractDetails']);
      }
      if (data.hasOwnProperty('startDate')) {
        obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('totalPaidAmount')) {
        obj['totalPaidAmount'] = ApiClient.convertToType(data['totalPaidAmount'], 'Number');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }
    return obj;
  }

  /**
   * ID.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Total payment amount. Formatted according to ISO 4217 standard.
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * Currency in ISO 4217 format.
   * @member {String} currency
   */
  exports.prototype['currency'] = undefined;
  /**
   * Default payment method for this contract.
   * @member {String} defaultPaymentMethodId
   */
  exports.prototype['defaultPaymentMethodId'] = undefined;
  /**
   * @member {module:model/ContractDevice} device
   */
  exports.prototype['device'] = undefined;
  /**
   * Amount of downpayment. Formatted according to ISO 4217 standard.
   * @member {Number} downpaymentAmount
   */
  exports.prototype['downpaymentAmount'] = undefined;
  /**
   * ID.
   * @member {String} downpaymentTransactionId
   */
  exports.prototype['downpaymentTransactionId'] = undefined;
  /**
   * Length of contract duration based on duration unit chosen. Minimum value is 1.
   * @member {Number} duration
   */
  exports.prototype['duration'] = undefined;
  /**
   * Time unit for length of contract. It can be DAY, WEEK or MONTH.
   * @member {String} durationUnit
   */
  exports.prototype['durationUnit'] = undefined;
  /**
   * Financier ID that owns this contract.
   * @member {String} financierId
   */
  exports.prototype['financierId'] = undefined;
  /**
   * @member {module:model/InstalmentContractDetail} instalmentContractDetails
   */
  exports.prototype['instalmentContractDetails'] = undefined;
  /**
   * Date time when contract is started. Default is null.
   * @member {Date} startDate
   */
  exports.prototype['startDate'] = undefined;
  /**
   * Status of contract. - CREATED; Contract is created but not started. - ACTIVE; Contract is started and active. - INACTIVE; Contract is started but inactive. Credit is not deducted and payment schedules are not active. Payment can no longer be made. - CANCELED; Contract is canceled. Credit is not deducted and payment schedules are not active. Payment can no longer be made. - COMPLETED; Contract is completed. Credit is not deducted and payment schedules are not active. Payment can no longer be made.  Default is CREATED 
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * Total amount paid. This is derived from the total amount of transactions happen for this contract.
   * @member {Number} totalPaidAmount
   */
  exports.prototype['totalPaidAmount'] = undefined;
  /**
   * Type of contract. Determine how payment is done. It can be CREDIT or INSTALMENT.
   * @member {String} type
   */
  exports.prototype['type'] = undefined;



  return exports;
}));


