/**
 * Pay On Demand for Digital Inclusion
 * Please visit https://developer.mastercard.com for additional details. ## Usage Notes - In the endpoints, you will see parameter examples in {{parameter}} format. You need to replace that with the actual value. This is usually applicable for identifier (ID). For example, on GET /contracts, you need to replace \"financier_id\" parameter with actual financier ID value. You can get this value either from querying using GET /financiers or creating a new financier using POST /financiers. The same applies for properties inside request body. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: PayonDemand_DigitalInclusion@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Financier'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Financier'));
  } else {
    // Browser globals (root is window)
    if (!root.PodApiClient) {
      root.PodApiClient = {};
    }
    root.PodApiClient.FinanciersAllOf = factory(root.PodApiClient.ApiClient, root.PodApiClient.Financier);
  }
}(this, function(ApiClient, Financier) {
  'use strict';



  /**
   * The FinanciersAllOf model module.
   * @module model/FinanciersAllOf
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>FinanciersAllOf</code>.
   * @alias module:model/FinanciersAllOf
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>FinanciersAllOf</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FinanciersAllOf} obj Optional instance to populate.
   * @return {module:model/FinanciersAllOf} The populated <code>FinanciersAllOf</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [Financier]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Financier>} items
   */
  exports.prototype['items'] = undefined;



  return exports;
}));


