/**
 * Pay On Demand for Digital Inclusion
 * Please visit https://developer.mastercard.com for additional details. ## Usage Notes - In the endpoints, you will see parameter examples in {{parameter}} format. You need to replace that with the actual value. This is usually applicable for identifier (ID). For example, on GET /contracts, you need to replace \"financier_id\" parameter with actual financier ID value. You can get this value either from querying using GET /financiers or creating a new financier using POST /financiers. The same applies for properties inside request body. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: PayonDemand_DigitalInclusion@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PodApiClient) {
      root.PodApiClient = {};
    }
    root.PodApiClient.Gateway = factory(root.PodApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Gateway model module.
   * @module model/Gateway
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Gateway</code>.
   * @alias module:model/Gateway
   * @class
   * @param id {String} ID.
   * @param code {String} Code. This is used to identify gateway.
   * @param configurationSchema {String} Schema used to describe configuration needed. Formatted in JSON Schema format.
   * @param name {String} Name.
   * @param version {String} Version. This is used in the case one payment gateway has multiple version.
   */
  var exports = function(id, code, configurationSchema, name, version) {
    var _this = this;

    _this['id'] = id;
    _this['code'] = code;
    _this['configurationSchema'] = configurationSchema;
    _this['name'] = name;
    _this['version'] = version;
  };

  /**
   * Constructs a <code>Gateway</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Gateway} obj Optional instance to populate.
   * @return {module:model/Gateway} The populated <code>Gateway</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'String');
      }
      if (data.hasOwnProperty('configurationSchema')) {
        obj['configurationSchema'] = ApiClient.convertToType(data['configurationSchema'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'String');
      }
    }
    return obj;
  }

  /**
   * ID.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Code. This is used to identify gateway.
   * @member {String} code
   */
  exports.prototype['code'] = undefined;
  /**
   * Schema used to describe configuration needed. Formatted in JSON Schema format.
   * @member {String} configurationSchema
   */
  exports.prototype['configurationSchema'] = undefined;
  /**
   * Name.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Version. This is used in the case one payment gateway has multiple version.
   * @member {String} version
   */
  exports.prototype['version'] = undefined;



  return exports;
}));


