/**
 * Pay On Demand for Digital Inclusion
 * Please visit https://developer.mastercard.com for additional details. ## Usage Notes - In the endpoints, you will see parameter examples in {{parameter}} format. You need to replace that with the actual value. This is usually applicable for identifier (ID). For example, on GET /contracts, you need to replace \"financier_id\" parameter with actual financier ID value. You can get this value either from querying using GET /financiers or creating a new financier using POST /financiers. The same applies for properties inside request body. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: PayonDemand_DigitalInclusion@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PodApiClient) {
      root.PodApiClient = {};
    }
    root.PodApiClient.InstalmentPaymentSchedule = factory(root.PodApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The InstalmentPaymentSchedule model module.
   * @module model/InstalmentPaymentSchedule
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>InstalmentPaymentSchedule</code>.
   * @alias module:model/InstalmentPaymentSchedule
   * @class
   * @param order {Number} Sequence number for this payment schedule.
   * @param amount {Number} Payment amount. Formatted according to ISO 4217 standard.
   * @param dueDate {Date} Due date
   * @param status {String} Status of payment schedule - UNPAID; not paid - PAID; paid 
   */
  var exports = function(order, amount, dueDate, status) {
    var _this = this;

    _this['order'] = order;
    _this['amount'] = amount;
    _this['dueDate'] = dueDate;
    _this['status'] = status;
  };

  /**
   * Constructs a <code>InstalmentPaymentSchedule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InstalmentPaymentSchedule} obj Optional instance to populate.
   * @return {module:model/InstalmentPaymentSchedule} The populated <code>InstalmentPaymentSchedule</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('order')) {
        obj['order'] = ApiClient.convertToType(data['order'], 'Number');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
      if (data.hasOwnProperty('dueDate')) {
        obj['dueDate'] = ApiClient.convertToType(data['dueDate'], 'Date');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * Sequence number for this payment schedule.
   * @member {Number} order
   */
  exports.prototype['order'] = undefined;
  /**
   * Payment amount. Formatted according to ISO 4217 standard.
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * Due date
   * @member {Date} dueDate
   */
  exports.prototype['dueDate'] = undefined;
  /**
   * Status of payment schedule - UNPAID; not paid - PAID; paid 
   * @member {String} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


