/**
 * Pay On Demand for Digital Inclusion
 * Please visit https://developer.mastercard.com for additional details. ## Usage Notes - In the endpoints, you will see parameter examples in {{parameter}} format. You need to replace that with the actual value. This is usually applicable for identifier (ID). For example, on GET /contracts, you need to replace \"financier_id\" parameter with actual financier ID value. You can get this value either from querying using GET /financiers or creating a new financier using POST /financiers. The same applies for properties inside request body. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: PayonDemand_DigitalInclusion@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PodApiClient) {
      root.PodApiClient = {};
    }
    root.PodApiClient.LineItem = factory(root.PodApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The LineItem model module.
   * @module model/LineItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>LineItem</code>.
   * @alias module:model/LineItem
   * @class
   * @param amount {String} Linet item amount. Formatted according to ISO 4217 standard.
   * @param lineItemDescription {String} Description of the line item.
   * @param lineItemType {String} Line item type values. - OTHER_FEE; Can be used to describe the amounts such as service charge, penalty etc. - INSTALMENT; Can be used to describe the installment amount. - DOWN_PAYMENT; Can be used to describe the down payment amount 
   * @param flag {Number} This flag is used to style the line item.
   */
  var exports = function(amount, lineItemDescription, lineItemType, flag) {
    var _this = this;

    _this['amount'] = amount;
    _this['lineItemDescription'] = lineItemDescription;
    _this['lineItemType'] = lineItemType;
    _this['flag'] = flag;
  };

  /**
   * Constructs a <code>LineItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LineItem} obj Optional instance to populate.
   * @return {module:model/LineItem} The populated <code>LineItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
      }
      if (data.hasOwnProperty('lineItemDescription')) {
        obj['lineItemDescription'] = ApiClient.convertToType(data['lineItemDescription'], 'String');
      }
      if (data.hasOwnProperty('lineItemType')) {
        obj['lineItemType'] = ApiClient.convertToType(data['lineItemType'], 'String');
      }
      if (data.hasOwnProperty('flag')) {
        obj['flag'] = ApiClient.convertToType(data['flag'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Linet item amount. Formatted according to ISO 4217 standard.
   * @member {String} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * Description of the line item.
   * @member {String} lineItemDescription
   */
  exports.prototype['lineItemDescription'] = undefined;
  /**
   * Line item type values. - OTHER_FEE; Can be used to describe the amounts such as service charge, penalty etc. - INSTALMENT; Can be used to describe the installment amount. - DOWN_PAYMENT; Can be used to describe the down payment amount 
   * @member {String} lineItemType
   */
  exports.prototype['lineItemType'] = undefined;
  /**
   * This flag is used to style the line item.
   * @member {Number} flag
   */
  exports.prototype['flag'] = undefined;



  return exports;
}));


