/**
 * Pay On Demand for Digital Inclusion
 * Please visit https://developer.mastercard.com for additional details. ## Usage Notes - In the endpoints, you will see parameter examples in {{parameter}} format. You need to replace that with the actual value. This is usually applicable for identifier (ID). For example, on GET /contracts, you need to replace \"financier_id\" parameter with actual financier ID value. You can get this value either from querying using GET /financiers or creating a new financier using POST /financiers. The same applies for properties inside request body. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: PayonDemand_DigitalInclusion@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CollectionPage', 'model/Contract', 'model/ContractCreateRequest', 'model/ContractDevice', 'model/ContractDeviceCreateRequest', 'model/ContractDeviceUpdateRequest', 'model/ContractUpdateRequest', 'model/Contracts', 'model/ContractsAllOf', 'model/CreditContractDetail', 'model/DeviceListing', 'model/DeviceResponse', 'model/Error', 'model/ErrorResponse', 'model/ErrorResponseErrors', 'model/Financier', 'model/FinancierCreateRequest', 'model/Financiers', 'model/FinanciersAllOf', 'model/Gateway', 'model/GatewayConfiguration', 'model/GatewayConfigurationRequest', 'model/GatewayConfigurationWeb', 'model/GatewayConfigurations', 'model/GatewayConfigurationsAllOf', 'model/Gateways', 'model/GatewaysAllOf', 'model/InstalmentContractDetail', 'model/InstalmentPaymentSchedule', 'model/LineItem', 'model/PaymentSession', 'model/PaymentSessionRequest', 'model/Transaction', 'model/TransactionRequest', 'model/Transactions', 'model/TransactionsAllOf', 'api/ContractsApi', 'api/DevicesApi', 'api/FinanciersApi', 'api/GatewayApi', 'api/GatewayConfigurationApi', 'api/PaymentSessionsApi', 'api/TransactionsApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/CollectionPage'), require('./model/Contract'), require('./model/ContractCreateRequest'), require('./model/ContractDevice'), require('./model/ContractDeviceCreateRequest'), require('./model/ContractDeviceUpdateRequest'), require('./model/ContractUpdateRequest'), require('./model/Contracts'), require('./model/ContractsAllOf'), require('./model/CreditContractDetail'), require('./model/DeviceListing'), require('./model/DeviceResponse'), require('./model/Error'), require('./model/ErrorResponse'), require('./model/ErrorResponseErrors'), require('./model/Financier'), require('./model/FinancierCreateRequest'), require('./model/Financiers'), require('./model/FinanciersAllOf'), require('./model/Gateway'), require('./model/GatewayConfiguration'), require('./model/GatewayConfigurationRequest'), require('./model/GatewayConfigurationWeb'), require('./model/GatewayConfigurations'), require('./model/GatewayConfigurationsAllOf'), require('./model/Gateways'), require('./model/GatewaysAllOf'), require('./model/InstalmentContractDetail'), require('./model/InstalmentPaymentSchedule'), require('./model/LineItem'), require('./model/PaymentSession'), require('./model/PaymentSessionRequest'), require('./model/Transaction'), require('./model/TransactionRequest'), require('./model/Transactions'), require('./model/TransactionsAllOf'), require('./api/ContractsApi'), require('./api/DevicesApi'), require('./api/FinanciersApi'), require('./api/GatewayApi'), require('./api/GatewayConfigurationApi'), require('./api/PaymentSessionsApi'), require('./api/TransactionsApi'));
  }
}(function(ApiClient, CollectionPage, Contract, ContractCreateRequest, ContractDevice, ContractDeviceCreateRequest, ContractDeviceUpdateRequest, ContractUpdateRequest, Contracts, ContractsAllOf, CreditContractDetail, DeviceListing, DeviceResponse, Error, ErrorResponse, ErrorResponseErrors, Financier, FinancierCreateRequest, Financiers, FinanciersAllOf, Gateway, GatewayConfiguration, GatewayConfigurationRequest, GatewayConfigurationWeb, GatewayConfigurations, GatewayConfigurationsAllOf, Gateways, GatewaysAllOf, InstalmentContractDetail, InstalmentPaymentSchedule, LineItem, PaymentSession, PaymentSessionRequest, Transaction, TransactionRequest, Transactions, TransactionsAllOf, ContractsApi, DevicesApi, FinanciersApi, GatewayApi, GatewayConfigurationApi, PaymentSessionsApi, TransactionsApi) {
  'use strict';

  /**
   * Please_visit_https__developer_mastercard_com_for_additional_details__Usage_Notes__In_the_endpoints_you_will_see_parameter_examples_in_parameter_format__You_need_to_replace_that_with_the_actual_value__This_is_usually_applicable_for_identifier__ID__For_example_on_GET__contracts_you_need_to_replace_financier_id_parameter_with_actual_financier_ID_value__You_can_get_this_value_either_from_querying_using_GET__financiers_or_creating_a_new_financier_using_POST__financiers__The_same_applies_for_properties_inside_request_body_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var PodApiClient = require('index'); // See note below*.
   * var xxxSvc = new PodApiClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new PodApiClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new PodApiClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new PodApiClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The CollectionPage model constructor.
     * @property {module:model/CollectionPage}
     */
    CollectionPage: CollectionPage,
    /**
     * The Contract model constructor.
     * @property {module:model/Contract}
     */
    Contract: Contract,
    /**
     * The ContractCreateRequest model constructor.
     * @property {module:model/ContractCreateRequest}
     */
    ContractCreateRequest: ContractCreateRequest,
    /**
     * The ContractDevice model constructor.
     * @property {module:model/ContractDevice}
     */
    ContractDevice: ContractDevice,
    /**
     * The ContractDeviceCreateRequest model constructor.
     * @property {module:model/ContractDeviceCreateRequest}
     */
    ContractDeviceCreateRequest: ContractDeviceCreateRequest,
    /**
     * The ContractDeviceUpdateRequest model constructor.
     * @property {module:model/ContractDeviceUpdateRequest}
     */
    ContractDeviceUpdateRequest: ContractDeviceUpdateRequest,
    /**
     * The ContractUpdateRequest model constructor.
     * @property {module:model/ContractUpdateRequest}
     */
    ContractUpdateRequest: ContractUpdateRequest,
    /**
     * The Contracts model constructor.
     * @property {module:model/Contracts}
     */
    Contracts: Contracts,
    /**
     * The ContractsAllOf model constructor.
     * @property {module:model/ContractsAllOf}
     */
    ContractsAllOf: ContractsAllOf,
    /**
     * The CreditContractDetail model constructor.
     * @property {module:model/CreditContractDetail}
     */
    CreditContractDetail: CreditContractDetail,
    /**
     * The DeviceListing model constructor.
     * @property {module:model/DeviceListing}
     */
    DeviceListing: DeviceListing,
    /**
     * The DeviceResponse model constructor.
     * @property {module:model/DeviceResponse}
     */
    DeviceResponse: DeviceResponse,
    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error: Error,
    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse: ErrorResponse,
    /**
     * The ErrorResponseErrors model constructor.
     * @property {module:model/ErrorResponseErrors}
     */
    ErrorResponseErrors: ErrorResponseErrors,
    /**
     * The Financier model constructor.
     * @property {module:model/Financier}
     */
    Financier: Financier,
    /**
     * The FinancierCreateRequest model constructor.
     * @property {module:model/FinancierCreateRequest}
     */
    FinancierCreateRequest: FinancierCreateRequest,
    /**
     * The Financiers model constructor.
     * @property {module:model/Financiers}
     */
    Financiers: Financiers,
    /**
     * The FinanciersAllOf model constructor.
     * @property {module:model/FinanciersAllOf}
     */
    FinanciersAllOf: FinanciersAllOf,
    /**
     * The Gateway model constructor.
     * @property {module:model/Gateway}
     */
    Gateway: Gateway,
    /**
     * The GatewayConfiguration model constructor.
     * @property {module:model/GatewayConfiguration}
     */
    GatewayConfiguration: GatewayConfiguration,
    /**
     * The GatewayConfigurationRequest model constructor.
     * @property {module:model/GatewayConfigurationRequest}
     */
    GatewayConfigurationRequest: GatewayConfigurationRequest,
    /**
     * The GatewayConfigurationWeb model constructor.
     * @property {module:model/GatewayConfigurationWeb}
     */
    GatewayConfigurationWeb: GatewayConfigurationWeb,
    /**
     * The GatewayConfigurations model constructor.
     * @property {module:model/GatewayConfigurations}
     */
    GatewayConfigurations: GatewayConfigurations,
    /**
     * The GatewayConfigurationsAllOf model constructor.
     * @property {module:model/GatewayConfigurationsAllOf}
     */
    GatewayConfigurationsAllOf: GatewayConfigurationsAllOf,
    /**
     * The Gateways model constructor.
     * @property {module:model/Gateways}
     */
    Gateways: Gateways,
    /**
     * The GatewaysAllOf model constructor.
     * @property {module:model/GatewaysAllOf}
     */
    GatewaysAllOf: GatewaysAllOf,
    /**
     * The InstalmentContractDetail model constructor.
     * @property {module:model/InstalmentContractDetail}
     */
    InstalmentContractDetail: InstalmentContractDetail,
    /**
     * The InstalmentPaymentSchedule model constructor.
     * @property {module:model/InstalmentPaymentSchedule}
     */
    InstalmentPaymentSchedule: InstalmentPaymentSchedule,
    /**
     * The LineItem model constructor.
     * @property {module:model/LineItem}
     */
    LineItem: LineItem,
    /**
     * The PaymentSession model constructor.
     * @property {module:model/PaymentSession}
     */
    PaymentSession: PaymentSession,
    /**
     * The PaymentSessionRequest model constructor.
     * @property {module:model/PaymentSessionRequest}
     */
    PaymentSessionRequest: PaymentSessionRequest,
    /**
     * The Transaction model constructor.
     * @property {module:model/Transaction}
     */
    Transaction: Transaction,
    /**
     * The TransactionRequest model constructor.
     * @property {module:model/TransactionRequest}
     */
    TransactionRequest: TransactionRequest,
    /**
     * The Transactions model constructor.
     * @property {module:model/Transactions}
     */
    Transactions: Transactions,
    /**
     * The TransactionsAllOf model constructor.
     * @property {module:model/TransactionsAllOf}
     */
    TransactionsAllOf: TransactionsAllOf,
    /**
     * The ContractsApi service constructor.
     * @property {module:api/ContractsApi}
     */
    ContractsApi: ContractsApi,
    /**
     * The DevicesApi service constructor.
     * @property {module:api/DevicesApi}
     */
    DevicesApi: DevicesApi,
    /**
     * The FinanciersApi service constructor.
     * @property {module:api/FinanciersApi}
     */
    FinanciersApi: FinanciersApi,
    /**
     * The GatewayApi service constructor.
     * @property {module:api/GatewayApi}
     */
    GatewayApi: GatewayApi,
    /**
     * The GatewayConfigurationApi service constructor.
     * @property {module:api/GatewayConfigurationApi}
     */
    GatewayConfigurationApi: GatewayConfigurationApi,
    /**
     * The PaymentSessionsApi service constructor.
     * @property {module:api/PaymentSessionsApi}
     */
    PaymentSessionsApi: PaymentSessionsApi,
    /**
     * The TransactionsApi service constructor.
     * @property {module:api/TransactionsApi}
     */
    TransactionsApi: TransactionsApi
  };

  return exports;
}));
