/**
 * Pay On Demand for Digital Inclusion
 * Please visit https://developer.mastercard.com for additional details. ## Usage Notes - In the endpoints, you will see parameter examples in {{parameter}} format. You need to replace that with the actual value. This is usually applicable for identifier (ID). For example, on GET /contracts, you need to replace \"financier_id\" parameter with actual financier ID value. You can get this value either from querying using GET /financiers or creating a new financier using POST /financiers. The same applies for properties inside request body. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: PayonDemand_DigitalInclusion@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorResponse', 'model/PaymentSession', 'model/PaymentSessionRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ErrorResponse'), require('../model/PaymentSession'), require('../model/PaymentSessionRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.PodApiClient) {
      root.PodApiClient = {};
    }
    root.PodApiClient.PaymentSessionsApi = factory(root.PodApiClient.ApiClient, root.PodApiClient.ErrorResponse, root.PodApiClient.PaymentSession, root.PodApiClient.PaymentSessionRequest);
  }
}(this, function(ApiClient, ErrorResponse, PaymentSession, PaymentSessionRequest) {
  'use strict';

  /**
   * PaymentSessions service.
   * @module api/PaymentSessionsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new PaymentSessionsApi. 
   * @alias module:api/PaymentSessionsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createPaymentSession operation.
     * @callback module:api/PaymentSessionsApi~createPaymentSessionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaymentSession} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new payment session
     * ##### Usage - Replace {{contract_id}} with an actual Contract ID before trying this endpoint.  - Replace {{financier_id}} with an actual Financier ID before trying this endpoint.  
     * @param {Object} opts Optional parameters
     * @param {module:model/PaymentSessionRequest} opts.paymentSessionRequest 
     * @param {module:api/PaymentSessionsApi~createPaymentSessionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaymentSession}
     */
    this.createPaymentSession = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['paymentSessionRequest'];

      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PaymentSession;
      return this.apiClient.callApi(
        '/payment-sessions', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }
  };

  return exports;
}));
