/**
 * Pay On Demand for Digital Inclusion
 * ## Usage Notes - In the endpoints, you will see parameter examples in {{parameter}} format. You need to replace that with the correct value. This is usually used for identifier (ID). For example, on GET /contracts, you need to replace \"financier_id\" parameter with actual financier ID. You can get this either from querying using GET /financiers or creating a new financier using POST /financiers. This also applies for properties inside request body.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: PayonDemand_DigitalInclusion@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.0
 *
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd() + '/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd() + '/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PodApiClient);
  }
})(this, function (expect, PodApiClient) {
  'use strict';

  var instance;

  beforeEach(function () {
    instance = new PodApiClient.ContractDevice();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') object[setter](value);
    else object[property] = value;
  };

  describe('ContractDevice', function () {
    it('should create an instance of ContractDevice', function () {
      // uncomment below and update the code to test ContractDevice
      var instance = new PodApiClient.ContractDevice();
      expect(instance).to.be.a(PodApiClient.ContractDevice);
    });

    it('should have the property deviceId (base name: "deviceId")', function () {
      // uncomment below and update the code to test the property deviceId
      var instance = new PodApiClient.ContractDevice();
      expect(instance).to.have.property('deviceId');
    });

    it('should have the property deviceIMEI (base name: "deviceIMEI")', function () {
      // uncomment below and update the code to test the property deviceIMEI
      var instance = new PodApiClient.ContractDevice();
      expect(instance).to.have.property('deviceIMEI');
    });

    it('should have the property oem (base name: "oem")', function () {
      // uncomment below and update the code to test the property oem
      var instance = new PodApiClient.ContractDevice();
      expect(instance).to.have.property('oem');
    });

    it('should have the property offlineLockTimestamp (base name: "offlineLockTimestamp")', function () {
      // uncomment below and update the code to test the property offlineLockTimestamp
      var instance = new PodApiClient.ContractDevice();
      expect(instance).to.have.property('offlineLockTimestamp');
    });

    it('should have the property model (base name: "model")', function () {
      // uncomment below and update the code to test the property model
      var instance = new PodApiClient.ContractDevice();
      expect(instance).to.have.property('model');
    });

    it('should have the property deviceSerialNumber (base name: "deviceSerialNumber")', function () {
      // uncomment below and update the code to test the property deviceSerialNumber
      var instance = new PodApiClient.ContractDevice();
      expect(instance).to.have.property('deviceSerialNumber');
    });

    it('should have the property status (base name: "status")', function () {
      // uncomment below and update the code to test the property status
      var instance = new PodApiClient.ContractDevice();
      expect(instance).to.have.property('status');
    });

    it('should copy from constructor argument', function () {
      const instance = new PodApiClient.ContractDevice(
        'device-id',
        'IMEI',
        'Samsung',
        '1587911148',
        'A10',
        '02394809ladjlks',
        'ACTIVE'
      );
      expect(instance).to.have.property('deviceId', 'device-id');
      expect(instance).to.have.property('deviceIMEI', 'IMEI');
      expect(instance).to.have.property('oem', 'Samsung');
      expect(instance).to.have.property('offlineLockTimestamp', '1587911148');
      expect(instance).to.have.property('model', 'A10');
      expect(instance).to.have.property(
        'deviceSerialNumber',
        '02394809ladjlks'
      );
      expect(instance).to.have.property('status', 'ACTIVE');
    });

    it('should copy to provided object even for empty data', function () {
      const instance = PodApiClient.ContractDevice.constructFromObject({});
      expect(instance).to.have.property('deviceId');
      expect(instance).to.have.property('deviceIMEI');
      expect(instance).to.have.property('oem');
      expect(instance).to.have.property('offlineLockTimestamp');
      expect(instance).to.have.property('model');
      expect(instance).to.have.property('deviceSerialNumber');
      expect(instance).to.have.property('status');
    });

    it('should copy to provided object', function () {
      const instance = {};
      PodApiClient.ContractDevice.constructFromObject(
        {
          deviceId: 'device-id',
          deviceIMEI: 'IMEI',
          oem: 'Samsung',
          offlineLockTimestamp: '1587911148',
          model: 'A10',
          deviceSerialNumber: '02394809ladjlks',
          status: 'ACTIVE',
        },
        instance
      );
      expect(instance).to.have.property('deviceId', 'device-id');
      expect(instance).to.have.property('deviceIMEI', 'IMEI');
      expect(instance).to.have.property('oem', 'Samsung');
      expect(instance).to.have.property('offlineLockTimestamp', 1587911148);
      expect(instance).to.have.property('model', 'A10');
      expect(instance).to.have.property(
        'deviceSerialNumber',
        '02394809ladjlks'
      );
      expect(instance).to.have.property('status', 'ACTIVE');
    });
  });
});
