/**
 * Pay On Demand for Digital Inclusion
 * ## Usage Notes - In the endpoints, you will see parameter examples in {{parameter}} format. You need to replace that with the correct value. This is usually used for identifier (ID). For example, on GET /contracts, you need to replace \"financier_id\" parameter with actual financier ID. You can get this either from querying using GET /financiers or creating a new financier using POST /financiers. This also applies for properties inside request body.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: PayonDemand_DigitalInclusion@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.0
 *
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd() + '/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd() + '/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PodApiClient);
  }
})(this, function (expect, PodApiClient) {
  'use strict';

  var instance;

  beforeEach(function () {
    instance = new PodApiClient.Error();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') object[setter](value);
    else object[property] = value;
  };

  describe('Error', function () {
    it('should create an instance of Error', function () {
      // uncomment below and update the code to test Error
      var instance = new PodApiClient.Error();
      expect(instance).to.be.a(PodApiClient.Error);
    });

    it('should have the property source (base name: "Source")', function () {
      // uncomment below and update the code to test the property source
      var instance = new PodApiClient.Error();
      expect(instance).to.have.property('Source');
    });

    it('should have the property reasonCode (base name: "ReasonCode")', function () {
      // uncomment below and update the code to test the property reasonCode
      var instance = new PodApiClient.Error();
      expect(instance).to.have.property('ReasonCode');
    });

    it('should have the property description (base name: "Description")', function () {
      // uncomment below and update the code to test the property description
      var instance = new PodApiClient.Error();
      expect(instance).to.have.property('Description');
    });

    it('should have the property recoverable (base name: "Recoverable")', function () {
      // uncomment below and update the code to test the property recoverable
      var instance = new PodApiClient.Error();
      expect(instance).to.have.property('Recoverable');
    });

    it('should have the property details (base name: "Details")', function () {
      // uncomment below and update the code to test the property details
      var instance = new PodApiClient.Error();
      expect(instance).to.have.property('Details');
    });

    it('should copy to provided object even for empty data', function () {
      const instance = PodApiClient.Error.constructFromObject({});
      expect(instance).to.have.property('Source');
      expect(instance).to.have.property('ReasonCode');
      expect(instance).to.have.property('Description');
      expect(instance).to.have.property('Recoverable');
      expect(instance).to.have.property('Details');
    });

    it('should copy to provided object', function () {
      const instance = {};
      PodApiClient.Error.constructFromObject(
        {
          Source: 'Authentication',
          ReasonCode: '403',
          Description: 'Unauthorized',
          Recoverable: false,
          Details: 'No role added',
        },
        instance
      );
      expect(instance).to.have.property('Source', 'Authentication');
      expect(instance).to.have.property('ReasonCode', '403');
      expect(instance).to.have.property('Description', 'Unauthorized');
      expect(instance).to.have.property('Recoverable', false);
      expect(instance).to.have.property('Details', 'No role added');
    });
  });
});
