/**
 * Pay On Demand for Digital Inclusion
 * ## Usage Notes - In the endpoints, you will see parameter examples in {{parameter}} format. You need to replace that with the correct value. This is usually used for identifier (ID). For example, on GET /contracts, you need to replace \"financier_id\" parameter with actual financier ID. You can get this either from querying using GET /financiers or creating a new financier using POST /financiers. This also applies for properties inside request body.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: PayonDemand_DigitalInclusion@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.0
 *
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd() + '/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd() + '/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PodApiClient);
  }
})(this, function (expect, PodApiClient) {
  'use strict';

  var instance;

  beforeEach(function () {
    instance = new PodApiClient.Gateway();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') object[setter](value);
    else object[property] = value;
  };

  describe('Gateway', function () {
    it('should create an instance of Gateway', function () {
      // uncomment below and update the code to test Gateway
      var instance = new PodApiClient.Gateway();
      expect(instance).to.be.a(PodApiClient.Gateway);
    });

    it('should have the property id (base name: "id")', function () {
      // uncomment below and update the code to test the property id
      var instance = new PodApiClient.Gateway();
      expect(instance).to.have.property('id');
    });

    it('should have the property code (base name: "code")', function () {
      // uncomment below and update the code to test the property code
      var instance = new PodApiClient.Gateway();
      expect(instance).to.have.property('code');
    });

    it('should have the property configurationSchema (base name: "configurationSchema")', function () {
      // uncomment below and update the code to test the property configurationSchema
      var instance = new PodApiClient.Gateway();
      expect(instance).to.have.property('configurationSchema');
    });

    it('should have the property name (base name: "name")', function () {
      // uncomment below and update the code to test the property name
      var instance = new PodApiClient.Gateway();
      expect(instance).to.have.property('name');
    });

    it('should have the property version (base name: "version")', function () {
      // uncomment below and update the code to test the property version
      var instance = new PodApiClient.Gateway();
      expect(instance).to.have.property('version');
    });

    it('should copy from constructor argument', function () {
      const instance = new PodApiClient.Gateway(
        'gateway-id',
        'gateway-code',
        'configuration-schema',
        'gateway name',
        '4'
      );
      expect(instance).to.have.property('id', 'gateway-id');
      expect(instance).to.have.property('code', 'gateway-code');
      expect(instance).to.have.property(
        'configurationSchema',
        'configuration-schema'
      );
      expect(instance).to.have.property('name', 'gateway name');
      expect(instance).to.have.property('version', '4');
    });

    it('should copy to provided object even for empty data', function () {
      const instance = PodApiClient.Gateway.constructFromObject({});
      expect(instance).to.have.property('id');
      expect(instance).to.have.property('code');
      expect(instance).to.have.property('configurationSchema');
      expect(instance).to.have.property('name');
      expect(instance).to.have.property('version');
    });

    it('should copy to provided object', function () {
      const instance = {};
      PodApiClient.Gateway.constructFromObject(
        {
          id: 'gateway-id',
          code: 'gateway-code',
          configurationSchema: 'configuration-schema',
          name: 'gateway name',
          version: '4',
        },
        instance
      );
      expect(instance).to.have.property('id', 'gateway-id');
      expect(instance).to.have.property('code', 'gateway-code');
      expect(instance).to.have.property(
        'configurationSchema',
        'configuration-schema'
      );
      expect(instance).to.have.property('name', 'gateway name');
      expect(instance).to.have.property('version', '4');
    });
  });
});
