/**
 * Pay On Demand for Digital Inclusion
 * ## Usage Notes - In the endpoints, you will see parameter examples in {{parameter}} format. You need to replace that with the correct value. This is usually used for identifier (ID). For example, on GET /contracts, you need to replace \"financier_id\" parameter with actual financier ID. You can get this either from querying using GET /financiers or creating a new financier using POST /financiers. This also applies for properties inside request body.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: PayonDemand_DigitalInclusion@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.0
 *
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd() + '/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd() + '/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PodApiClient);
  }
})(this, function (expect, PodApiClient) {
  'use strict';

  var instance;

  beforeEach(function () {
    instance = new PodApiClient.PaymentSession();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') object[setter](value);
    else object[property] = value;
  };

  describe('PaymentSession', function () {
    it('should create an instance of PaymentSession', function () {
      // uncomment below and update the code to test PaymentSession
      var instance = new PodApiClient.PaymentSession();
      expect(instance).to.be.a(PodApiClient.PaymentSession);
    });

    it('should have the property id (base name: "id")', function () {
      // uncomment below and update the code to test the property id
      var instance = new PodApiClient.PaymentSession();
      expect(instance).to.have.property('id');
    });

    it('should have the property financierId (base name: "financierId")', function () {
      // uncomment below and update the code to test the property financierId
      var instance = new PodApiClient.PaymentSession();
      expect(instance).to.have.property('financierId');
    });

    it('should have the property contractId (base name: "contractId")', function () {
      // uncomment below and update the code to test the property contractId
      var instance = new PodApiClient.PaymentSession();
      expect(instance).to.have.property('contractId');
    });

    it('should have the property defaultPaymentMethodId (base name: "defaultPaymentMethodId")', function () {
      // uncomment below and update the code to test the property defaultPaymentMethodId
      var instance = new PodApiClient.PaymentSession();
      expect(instance).to.have.property('defaultPaymentMethodId');
    });

    it('should have the property gatewayConfiguration (base name: "gatewayConfiguration")', function () {
      // uncomment below and update the code to test the property gatewayConfiguration
      var instance = new PodApiClient.PaymentSession();
      expect(instance).to.have.property('gatewayConfiguration');
    });

    it('should have the property orderId (base name: "orderId")', function () {
      // uncomment below and update the code to test the property orderId
      var instance = new PodApiClient.PaymentSession();
      expect(instance).to.have.property('orderId');
    });

    it('should have the property podTransactionId (base name: "podTransactionId")', function () {
      // uncomment below and update the code to test the property podTransactionId
      var instance = new PodApiClient.PaymentSession();
      expect(instance).to.have.property('podTransactionId');
    });

    it('should have the property totalAmount (base name: "totalAmount")', function () {
      // uncomment below and update the code to test the property totalAmount
      var instance = new PodApiClient.PaymentSession();
      expect(instance).to.have.property('totalAmount');
    });

    it('should have the property currency (base name: "currency")', function () {
      // uncomment below and update the code to test the property currency
      var instance = new PodApiClient.PaymentSession();
      expect(instance).to.have.property('currency');
    });

    it('should have the property lightBoxUrl (base name: "lightBoxUrl")', function () {
      // uncomment below and update the code to test the property lightBoxUrl
      var instance = new PodApiClient.PaymentSession();
      expect(instance).to.have.property('lightBoxUrl');
    });

    it('should have the property lineItems (base name: "lineItems")', function () {
      // uncomment below and update the code to test the property lineItems
      var instance = new PodApiClient.PaymentSession();
      expect(instance).to.have.property('lineItems');
    });

    it('should copy from constructor argument', function () {
      const instance = new PodApiClient.PaymentSession(
        'session-id',
        'fin-id',
        'contract-id',
        'lksadfhj98',
        'gateway-configuration',
        '02394809ladjlks',
        '54334rfgsd',
        '591',
        'NGN',
        'https://pod-financier.com',
        []
      );
      expect(instance).to.have.property('id', 'session-id');
      expect(instance).to.have.property('financierId', 'fin-id');
      expect(instance).to.have.property('contractId', 'contract-id');
      expect(instance).to.have.property('defaultPaymentMethodId', 'lksadfhj98');
      expect(instance).to.have.property(
        'gatewayConfiguration',
        'gateway-configuration'
      );
      expect(instance).to.have.property('orderId', '02394809ladjlks');
      expect(instance).to.have.property('podTransactionId', '54334rfgsd');
      expect(instance).to.have.property('totalAmount', '591');
      expect(instance).to.have.property('currency', 'NGN');
      expect(instance).to.have.property(
        'lightBoxUrl',
        'https://pod-financier.com'
      );
      expect(instance).to.have.property('lineItems');
      expect(instance.lineItems).to.be.empty();
    });

    it('should copy to provided object even for empty data', function () {
      const instance = PodApiClient.PaymentSession.constructFromObject({});
      expect(instance).to.have.property('id');
      expect(instance).to.have.property('financierId');
      expect(instance).to.have.property('contractId');
      expect(instance).to.have.property('defaultPaymentMethodId');
      expect(instance).to.have.property('gatewayConfiguration');
      expect(instance).to.have.property('orderId');
      expect(instance).to.have.property('podTransactionId');
      expect(instance).to.have.property('totalAmount');
      expect(instance).to.have.property('currency');
      expect(instance).to.have.property('lightBoxUrl');
      expect(instance).to.have.property('lineItems');
    });

    it('should copy to provided object', function () {
      const instance = {};
      PodApiClient.PaymentSession.constructFromObject(
        {
          id: 'session-id',
          financierId: 'fin-id',
          contractId: 'contract-id',
          defaultPaymentMethodId: 'lksadfhj98',
          gatewayConfiguration: {
            code: 'gateway-code',
            gatewayId: 'gateway-id',
            baseUrl: 'https://mpgs-gateway.org',
            merchantId: 'dsakljh7986',
            version: 14,
          },
          orderId: '02394809ladjlks',
          podTransactionId: '54334rfgsd',
          totalAmount: '591',
          currency: 'NGN',
          lightBoxUrl: 'https://pod-financier.com',
          lineItems: [],
        },
        instance
      );
      expect(instance).to.have.property('id', 'session-id');
      expect(instance).to.have.property('financierId', 'fin-id');
      expect(instance).to.have.property('contractId', 'contract-id');
      expect(instance).to.have.property('defaultPaymentMethodId', 'lksadfhj98');
      expect(instance).to.have.property('gatewayConfiguration');
      expect(instance).to.have.property('orderId', '02394809ladjlks');
      expect(instance).to.have.property('podTransactionId', '54334rfgsd');
      expect(instance).to.have.property('totalAmount', '591');
      expect(instance).to.have.property('currency', 'NGN');
      expect(instance).to.have.property(
        'lightBoxUrl',
        'https://pod-financier.com'
      );
      expect(instance).to.have.property('lineItems');
      expect(instance.lineItems).to.be.empty();
    });
  });
});
