/**
 * Pay On Demand for Digital Inclusion
 * ## Usage Notes - In the endpoints, you will see parameter examples in {{parameter}} format. You need to replace that with the correct value. This is usually used for identifier (ID). For example, on GET /contracts, you need to replace \"financier_id\" parameter with actual financier ID. You can get this either from querying using GET /financiers or creating a new financier using POST /financiers. This also applies for properties inside request body.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: PayonDemand_DigitalInclusion@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.0
 *
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd() + '/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd() + '/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PodApiClient);
  }
})(this, function (expect, PodApiClient) {
  'use strict';

  var instance;

  beforeEach(function () {
    instance = new PodApiClient.PaymentSessionRequest();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') object[setter](value);
    else object[property] = value;
  };

  describe('PaymentSessionRequest', function () {
    it('should create an instance of PaymentSessionRequest', function () {
      // uncomment below and update the code to test PaymentSessionRequest
      var instance = new PodApiClient.PaymentSessionRequest();
      expect(instance).to.be.a(PodApiClient.PaymentSessionRequest);
    });

    it('should have the property financierId (base name: "financierId")', function () {
      // uncomment below and update the code to test the property financierId
      var instance = new PodApiClient.PaymentSessionRequest();
      expect(instance).to.have.property('financierId');
    });

    it('should have the property contractId (base name: "contractId")', function () {
      // uncomment below and update the code to test the property contractId
      var instance = new PodApiClient.PaymentSessionRequest();
      expect(instance).to.have.property('contractId');
    });

    it('should have the property deviceId (base name: "deviceId")', function () {
      // uncomment below and update the code to test the property deviceId
      var instance = new PodApiClient.PaymentSessionRequest();
      expect(instance).to.have.property('deviceId');
    });

    it('should have the property scope (base name: "scope")', function () {
      // uncomment below and update the code to test the property scope
      var instance = new PodApiClient.PaymentSessionRequest();
      expect(instance).to.have.property('scope');
    });

    it('should have the property totalAmount (base name: "totalAmount")', function () {
      // uncomment below and update the code to test the property totalAmount
      var instance = new PodApiClient.PaymentSessionRequest();
      expect(instance).to.have.property('totalAmount');
    });

    it('should have the property expiryDate (base name: "expiryDate")', function () {
      // uncomment below and update the code to test the property expiryDate
      var instance = new PodApiClient.PaymentSessionRequest();
      expect(instance).to.have.property('expiryDate');
    });

    it('should have the property callBackUrl (base name: "callBackUrl")', function () {
      // uncomment below and update the code to test the property callBackUrl
      var instance = new PodApiClient.PaymentSessionRequest();
      expect(instance).to.have.property('callBackUrl');
    });

    it('should have the property lineItems (base name: "lineItems")', function () {
      // uncomment below and update the code to test the property lineItems
      var instance = new PodApiClient.PaymentSessionRequest();
      expect(instance).to.have.property('lineItems');
    });

    it('should copy from constructor argument', function () {
      const instance = new PodApiClient.PaymentSessionRequest(
        'financier-id',
        'contract-id',
        'device-id',
        'scope',
        '508',
        '11-11-2011',
        'https://pod-financier.com',
        []
      );
      expect(instance).to.have.property('financierId', 'financier-id');
      expect(instance).to.have.property('contractId', 'contract-id');
      expect(instance).to.have.property('deviceId', 'device-id');
      expect(instance).to.have.property('scope', 'scope');
      expect(instance).to.have.property('totalAmount', '508');
      expect(instance).to.have.property('expiryDate', '11-11-2011');
      expect(instance).to.have.property(
        'callBackUrl',
        'https://pod-financier.com'
      );
      expect(instance).to.have.property('lineItems');
    });

    it('should copy to provided object even for empty data', function () {
      const instance = PodApiClient.PaymentSessionRequest.constructFromObject(
        {}
      );
      expect(instance).to.have.property('financierId');
      expect(instance).to.have.property('contractId');
      expect(instance).to.have.property('deviceId');
      expect(instance).to.have.property('scope');
      expect(instance).to.have.property('totalAmount');
      expect(instance).to.have.property('expiryDate');
      expect(instance).to.have.property('callBackUrl');
      expect(instance).to.have.property('lineItems');
    });

    it('should copy to provided object', function () {
      const instance = {};
      PodApiClient.PaymentSessionRequest.constructFromObject(
        {
          financierId: 'financier-id',
          contractId: 'contract-id',
          deviceId: 'device-id',
          scope: 'scope',
          totalAmount: '508',
          expiryDate: '11-11-2011',
          callBackUrl: 'https://pod-financier.com',
          lineItems: [],
        },
        instance
      );
      expect(instance).to.have.property('financierId', 'financier-id');
      expect(instance).to.have.property('contractId', 'contract-id');
      expect(instance).to.have.property('deviceId', 'device-id');
      expect(instance).to.have.property('scope', 'scope');
      expect(instance).to.have.property('totalAmount', '508');
      expect(instance).to.have.property('expiryDate', '11-11-2011');
      expect(instance).to.have.property(
        'callBackUrl',
        'https://pod-financier.com'
      );
      expect(instance).to.have.property('lineItems');
    });
  });
});
